"use client"

import * as React from "react"
import { X, Download } from "lucide-react"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Separator } from "@/components/ui/separator"

type NotebookDetailProps = {
  open: boolean
  onOpenChange: (open: boolean) => void
  title: string
  domain: string
  crawledContent: {
    markdown: string
    pdfs: string[]
    links: string[]
  }
}

export function NotebookDetail({
  open,
  onOpenChange,
  title,
  domain,
  crawledContent,
}: NotebookDetailProps) {
  const sourceCount = 1 + crawledContent.pdfs.length + crawledContent.links.length

  const handleExport = () => {
    const content = `# ${title}

Source: ${domain}
Created: ${new Date().toLocaleDateString()}
Total Sources: ${sourceCount}

## Main Content

${crawledContent.markdown?.slice(0, 2000) || "No content"}

## PDFs Found (${crawledContent.pdfs.length})

${crawledContent.pdfs.map((pdf, i) => `${i + 1}. ${pdf}`).join("\n")}

## Related Links (${crawledContent.links.length})

${crawledContent.links.slice(0, 10).map((link, i) => `${i + 1}. ${link}`).join("\n")}

---
Generated by LazyNotebookLM
`

    const blob = new Blob([content], { type: "text/markdown" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${title.replace(/\s+/g, "-").toLowerCase()}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle>{title}</DialogTitle>
        </DialogHeader>

        <div className="space-y-4">
          <div>
            <div className="text-sm font-medium text-muted-foreground">Domain</div>
            <div className="text-sm">{domain}</div>
          </div>

          <Separator />

          <div className="grid grid-cols-3 gap-4">
            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm">Main Content</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">1</div>
                <p className="text-xs text-muted-foreground">Markdown page</p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm">PDFs</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{crawledContent.pdfs.length}</div>
                <p className="text-xs text-muted-foreground">PDF files</p>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="pb-2">
                <CardTitle className="text-sm">Links</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">{crawledContent.links.length}</div>
                <p className="text-xs text-muted-foreground">Sub-pages</p>
              </CardContent>
            </Card>
          </div>

          <Separator />

          <div className="space-y-2">
            <div className="text-sm font-medium">Preview</div>
            <div className="rounded bg-muted p-3 text-xs leading-relaxed max-h-48 overflow-y-auto">
              <code>{crawledContent.markdown?.slice(0, 500)}...</code>
            </div>
          </div>

          <Separator />

          <div className="flex gap-2 justify-between">
            <Button variant="outline" size="sm" onClick={() => onOpenChange(false)}>
              <X className="size-4" />
              Close
            </Button>
            <Button size="sm" onClick={handleExport}>
              <Download className="size-4" />
              Export as Markdown
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}
